version: "3.7"
services:
  dms_client_app:
    build:
      context: .
    container_name: dms_client_app
    image: aarrunyal/dms_client_app:latest
    env_file: ./.env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - dms_client_network

networks:
  dms_client_network:
    name: dms_client_network
